SOURCE_DIRECTORY=../sources/

SRCS=$(SOURCE_DIRECTORY)/test.cpp  
#SRCS=$(SOURCE_DIRECTORY)/test_dataflow.cpp  

# Root directory path for the HLS libraries. Modify as necessary. 
SHLS_LIBRARY_DIR =  ../../../../..

USER_CXX_FLAG += -I$(SHLS_LIBRARY_DIR)

LOCAL_CONFIG = -legup-config=config.tcl
