#SRCS=test_dma.cpp  
#SRCS=test_no_dma.cpp  
SRCS=test_initiator.cpp  
LOCAL_CONFIG = -legup-config=config.tcl
LEVEL = $(SHLS_ROOT_DIR)/examples
USER_CXX_FLAG+=-I../../../../../
include $(LEVEL)/Makefile.common
