
NAME = fft
LOCAL_CONFIG = -legup-config=config.tcl
SRCS = test.cpp



USER_CXX_FLAG += -O3 -pg -Wall -Wno-strict-aliasing -Wno-unused-label -Wno-unknown-pragmas -Wno-attributes -I$(SHLS_ROOT_DIR)/smarthls-library
SHLS_LIBRARY_DIR=../../../..
USER_CXX_FLAG += -I$(SHLS_LIBRARY_DIR)/dsp/include -I$(SHLS_LIBRARY_DIR)/dsp/examples



