SOURCE_DIRECTORY=../sources

SRCS=$(SOURCE_DIRECTORY)/test.cpp  
#SRCS=$(SOURCE_DIRECTORY)/test_dataflow.cpp  

SHLS_MATH_LIBRARY = ../../../../

USER_CXX_FLAG += -I$(SHLS_MATH_LIBRARY)

LOCAL_CONFIG = -legup-config=config.tcl
