SOURCE_DIRECTORY=../sources

SRCS=$(SOURCE_DIRECTORY)/test.cpp  
#SRCS=$(SOURCE_DIRECTORY)/test_dataflow.cpp  

SHLS_LIBRARY = ../../../../..

USER_CXX_FLAG += -I$(SHLS_LIBRARY)

LOCAL_CONFIG = -legup-config=config.tcl
