<project name="VIDEO_KIT_TOP" version="1.2">
    <ProjectDirectory>
        C:\Users\c79828\Documents\HLS_Work\fpga-hls-libraries\vision\demo_designs\pfvk_agc_color_brightness\libero\VIDEO_KIT_TOP
    </ProjectDirectory>
    <View>
        ChainView
    </View>
    <LiberoTargetDevice>
        
    </LiberoTargetDevice>
    <LogFile>
        C:\Users\c79828\Documents\HLS_Work\fpga-hls-libraries\vision\demo_designs\pfvk_agc_color_brightness\libero\VIDEO_KIT_TOP\VIDEO_KIT_TOP.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <ProgrammingInterface>
        JTAGMode
    </ProgrammingInterface>
    <Servers>
    </Servers>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
            <FlashPro5>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    DiscreteClk
                </ClkMode>
            </FlashPro5>
            <FlashPro6>
                <TCK>
                    4000000
                </TCK>
                <SCK>
                    20000000
                </SCK>
                <ClkMode>
                    DiscreteClk
                </ClkMode>
            </FlashPro6>
        </Hardware>
        <Device type="ACTEL">
            <Name>
                MPF300TS
            </Name>
            <Custom>
                MPF300TS
            </Custom>
            <SpiFlashFile>
                C:\Users\c79828\Documents\HLS_Work\fpga-hls-libraries\vision\demo_designs\pfvk_agc_color_brightness\libero\VIDEO_KIT_TOP\VIDEO_KIT_TOP.bin
            </SpiFlashFile>
            <SpiFlashSelectedAction>
                
            </SpiFlashSelectedAction>
            <Algo type="PDB">
                <filename>
                    C:\Users\c79828\Documents\HLS_Work\fpga-hls-libraries\vision\demo_designs\pfvk_agc_color_brightness\libero\VIDEO_KIT_TOP\VIDEO_KIT_TOP.ppd
                </filename>
                <local>
                    projectData\VIDEO_KIT_TOP.ppd
                </local>
                <SelectedAction>
                    PROGRAM
                </SelectedAction>
                <DeselectedProcedure>
                    DO_VERIFY
                </DeselectedProcedure>
                <Action name="PROGRAM" deselectedProcedures="DO_VERIFY">
                </Action>
            </Algo>
        </Device>
        <Algo type="unknown">
            <irlength>
                0
            </irlength>
            <MaxTCK>
                0
            </MaxTCK>
        </Algo>
    </configuration>
</project>
