SRCS=bilinear_filter.cpp
LOCAL_CONFIG = -legup-config=config.tcl
# Allows an NeighborPixelTable instance to be constructed at compile-time
# NeighborPixelTable struct is used when the image type is frame buffer
# USER_CXX_FLAG += -fconstexpr-loop-limit=1000000

include Makefile.user
