SRCS=test_dma.cpp  
#SRCS=test_no_dma.cpp  
# SRCS=test_initiator.cpp  
LOCAL_CONFIG = -legup-config=config.tcl
LEVEL = $(SHLS_ROOT_DIR)/examples

SHLS_MATH_LIBRARY=$(SHLS_ROOT_DIR)/smarthls-library/external/math/
USER_CXX_FLAG+=-I$(SHLS_MATH_LIBRARY) -I$(SHLS_ROOT_DIR)/smarthls-library

