SRCS = ../sources/test.cpp

SHLS_LIBRARY = ../../../../..

USER_CXX_FLAG += -I$(SHLS_LIBRARY) 
USER_CXX_FLAG += -I$(SHLS_ROOT_DIR)/smarthls-library 
USER_CXX_FLAG += -D__N_ELEM=12800

LOCAL_CONFIG = -legup-config=config.tcl


