SRCS = ../sources/test.cpp  

SHLS_MATH_LIBRARY = ../../../../

USER_CXX_FLAG += -I$(SHLS_MATH_LIBRARY) 
USER_CXX_FLAG += -I$(SHLS_ROOT_DIR)/smarthls-library 
USER_CXX_FLAG += -D__N_ELEM=12800

NUM_LIBERO_PnR_PASSES=10

LOCAL_CONFIG = -legup-config=config.tcl
LEVEL = $(SHLS_ROOT_DIR)/examples
