SRCS = ../sources/test.cpp  

# Root directory path for the HLS libraries. Modify as necessary. 
SHLS_LIBRARY_DIR =  ../../../../..

USER_CXX_FLAG += -I$(SHLS_LIBRARY_DIR) 
USER_CXX_FLAG += -I$(SHLS_ROOT_DIR)/smarthls-library 
USER_CXX_FLAG += -D__N_ELEM=12800

NUM_LIBERO_PnR_PASSES=10

LOCAL_CONFIG = -legup-config=config.tcl

